# Service
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  name: postgres
  labels:
    component: postgres
spec:
  ports:
    - port: 5432
      name: db
    - port: 9187
      name: metrics
  selector:
    component: postgres
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    component: postgres
spec:
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
      - image: bitnami/postgres-exporter:0.8.0-debian-10-r28
        name: postgres-exporter
        env:
          - name: DATA_SOURCE_URI
            value: "localhost/test_db?sslmode=disable"
          - name: PG_EXPORTER_EXCLUDE_DATABASES
            value: template0,template1,postgres
          #- name: PG_EXPORTER_EXTEND_QUERY_PATH
          #  value: /opt/bitnami/postgres-exporter/queries/queries.yaml
          #- name: PG_EXPORTER_DISABLE_DEFAULT_METRIC
          #  value: "true"
          - name: PG_EXPORTER_DISABLE_SETTINGS_METRICS
            value: "true"
          - name: DATA_SOURCE_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PG_USERNAME
          - name: DATA_SOURCE_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PG_PASSWORD
        ports:
          - name: http-metrics
            containerPort: 9187
        volumeMounts:
          - name: postgres-queries
            mountPath: /opt/bitnami/postgres-exporter/queries
      - image: bitnami/postgresql:12-debian-10
        name: postgres
        resources:
          limits:
            memory: 2000Mi
            cpu: 1.0
          requests:
            memory: 2000Mi
            cpu: 1.0
        env:
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PG_DATABASE
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PG_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PG_PASSWORD
          - name: POSTGRESQL_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PG_POSTGRES_PASSWORD
          - name: BITNAMI_DEBUG
            value: "true"
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
          - name: postgres-init
            mountPath: /docker-entrypoint-initdb.d
          - name: postgres-conf
            mountPath: /opt/bitnami/postgresql/conf/conf.d
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - test_user
            - -d
            - test_db
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
        - name: postgres-storage
          emptyDir: {}
        - name: postgres-queries
          configMap:
            name: postgres-queries
        - name: postgres-init
          configMap:
            name: postgres-init
            items:
            - key: stat.sh
              path: stat.sh
        - name: postgres-conf
          configMap:
            name: postgres-init
            items:
            - key: stat.conf
              path: stat.conf
