apiVersion: redskyops.dev/v1alpha1
kind: Experiment
metadata:
  name: elasticsearch-example-free-tier-beam
spec:
  optimization:
  - name: experimentBudget
    value: "5"
  parameters:
  - name: memory
    min: 1000
    max: 2000
  - name: cpu
    min: 500
    max: 1000
  - name: heap_percent
    min: 20
    max: 80
  metrics:
  - name: duration
    minimize: true
    query: "{{duration .StartTime .CompletionTime}}"
  - name: cost
    minimize: true
    type: pods
    # Note that these cost weights are specific to GKE and represent $22/month/cpu and $3/month/GB
    query: '{{resourceRequests .Pods "cpu=0.022,memory=0.000000000003"}}'
    selector:
      matchLabels:
        app: elasticsearch
  template: # trial
    spec:
      setupTasks:
      - name: elasticsearch
        helmChart: elasticsearch
        helmChartVersion: 7.9.1
        helmRepository: https://helm.elastic.co
        helmValues:
        - name: cluster.name
          value: rally-demo
        - name: resources.limits.cpu
          value: "{{ .Values.cpu }}m"
        - name: resources.limits.memory
          value: "{{ .Values.memory }}Mi"
        - name: resources.requests.cpu
          value: "{{ .Values.cpu }}m"
        - name: resources.requests.memory
          value: "{{ .Values.memory }}Mi"
        - name: esJavaOpts
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ percent .Values.memory .Values.heap_percent }}m -Xmx{{ percent .Values.memory .Values.heap_percent }}m"
        - name: persistence.enabled
          value: "false"
        - name: antiAffinity
          value: soft
      # ES takes a while to come up as Ready 1/1
      initialDelaySeconds: 90
      setupServiceAccountName: redsky
      ttlSecondsAfterFinished: 1800
      template: # job
        spec:
          template: # pod
            spec:
              activeDeadlineSeconds: 1800
              containers:
              - image: elastic/rally:2.0.1
                name: rally
                args:
                - --track=geopoint
                - --target-hosts=elasticsearch-master-1
                - --pipeline=benchmark-only
                - --challenge=append-fast-with-conflicts
                - --track-params=ingest_percentage:50
                - --distribution-version=7.9.1
                volumeMounts:
                  - name: config
                    mountPath: /rally/.rally/rally.ini
                    subPath: rally-config
              volumes:
                - name: config
                  configMap:
                    name: rally-ini
