apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2020-09-22T21:31:00Z"
  generation: 1
  labels:
    app: rally
    manager: kubectl
    operation: Update
  name: rally
  namespace: default
  resourceVersion: "15314"
  selfLink: /apis/apps/v1/namespaces/default/deployments/rally
  uid: 9f08cfe3-5f37-4284-b1c6-643c42b8192a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rally
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rally
    spec:
      containers:
      - image: elastic/rally:2.0.1
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        args:
        - -c
        - "sleep 92309123"
        name: rally
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
