apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../locust-metrics

patches:
- path: ./resources_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: db
- path: ./resources_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: redis
- path: ./resources_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: result-service
- path: ./resources_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: result-exporter
- path: ./resources_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: voting-service
- path: ./resources_patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: worker
